export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const AUTH_LOADING = "AUTH_LOADING";

export const IMAGE_UPLOAD = "IMAGE_UPLOAD";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const GET_BASKETS = "GET_BASKETS";
export const TOGGLE_BASKET = "TOGGLE_BASKET";
export const UPDATE_BASKET = "UPDATE_BASKET";
export const BASKET_ERROR = "BASKET_ERROR";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const UPDATE_BASKET_PRODUCT = "UPDATE_BASKET_PRODUCT";
export const DELETE_PRODUCT_FROM_BASKET = "DELETE_PRODUCT_FROM_BASKET";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_SLIDES = "GET_SLIDES";
export const NEW_SLIDE = "NEW_SLIDE";
export const DELETE_SLIDE = "DELETE_SLIDE";
export const SLIDES_ERROR = "SLIDES_ERROR";
export const CURRENT_SLIDE = "CURRENT_SLIDE";

export const GET_PROJECTS = "GET_PROJECTS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const SET_SLIDE_DIMENSION = "SET_SLIDE_DIMENSION";
export const PROJECTS_ERROR = "PROJECTS_ERROR";
export const ADD_PROJECT = "ADD_PROJECT";
export const SAVE_PROJECT = "SAVE_PROJECT";

export const GET_IMAGES = "GET_IMAGES";
export const ADD_IMAGE = "ADD_IMAGE";
export const IMAGE_ERROR = "IMAGE_ERROR";

export const SET_IMAGE_TYPE = "SET_IMAGE_TYPE";
export const SET_DRAG_START = "SET_DRAG_START";
export const SET_BACKGROUND_EDIT = "SET_BACKGROUND_EDIT";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOAD_OBJECTS = "LOAD_OBJECTS";
export const LOAD_CONTAINERS = "LOAD_CONTAINERS";
export const LOAD_BACKGROUNDS = "LOAD_BACKGROUNDS";
export const LOAD_ERROR = "LOAD_ERROR";
export const UPDATE_HISTORY = "UPDATE_HISTORY";
export const ADD_OBJECT = "ADD_OBJECT";
export const SET_BACKGROUND_IMAGE = "SET_BACKGROUND_IMAGE";
export const REMOVE_OBJECT = "REMOVE_OBJECT";
export const UNDO = "UNDO";
export const REDO = "REDO";
export const UNDO_ERROR = "UNDO_ERROR";
export const REDO_ERROR = "REDO_ERROR";

export const ADD_LAYOUT = "ADD_LAYOUT";
export const UPDATE_OBJECT = "UPDATE_OBJECT";
export const UPDATE_CONTAINER = "UPDATE_CONTAINER";
export const UPDATE_GROUP_CONTAINER = "UPDATE_GROUP_CONTAINER";
export const UPDATE_BACKGROUND = "UPDATE_BACKGROUND";
export const SET_BACKGROUNDS = "SET_BACKGROUNDS";
